create database ChuyenDoiERD;
use ChuyenDoiERD;

-- PHIEUXUAT
CREATE TABLE PHIEUXUAT (
    SoPX VARCHAR(20) PRIMARY KEY,
    NgayXuat DATE
);

-- VATTU
CREATE TABLE VATTU (
    MaVTU VARCHAR(20) PRIMARY KEY,
    TenVTU VARCHAR(50)
);

-- PHIEUNHAP
CREATE TABLE PHIEUNHAP (
    SoPN VARCHAR(20) PRIMARY KEY,
    NgayNhap DATE
);

-- DONDH
CREATE TABLE DONDH (
    SoDH VARCHAR(20) PRIMARY KEY,
    NgayDH DATE
);

-- NHACC
CREATE TABLE NHACC (
    MaNCC VARCHAR(20) PRIMARY KEY,
    TenNCC VARCHAR(100),
    DiaChi VARCHAR(255),
    SDT VARCHAR(20)
);

-- Bảng quan hệ giũa phiếu xuất và vật tư
CREATE TABLE CHITIETPHIEUXUAT (
    SoPX VARCHAR(20),
    MaVTU VARCHAR(20),
    DGXuat INT,
    SLXuat INT,
    PRIMARY KEY (SoPX, MaVTU),
    FOREIGN KEY (SoPX) REFERENCES PHIEUXUAT(SoPX),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

-- Bảng quan hệ giữa vật tư và phiếu nhập
CREATE TABLE CHITIETPHIEUNHAP (
    SoPN VARCHAR(20),
    MaVTU VARCHAR(20),
    DGNhap DECIMAL(10, 2),
    SLNhap INT,
    PRIMARY KEY (SoPN, MaVTU),
    FOREIGN KEY (SoPN) REFERENCES PHIEUNHAP(SoPN),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

-- Bảng quan hệ giữa vật tư và đơn đặt hàng
CREATE TABLE CHITIETDONDH (
    SoDH VARCHAR(20),
    MaVTU VARCHAR(20),
    PRIMARY KEY (SoDH, MaVTU),
    FOREIGN KEY (SoDH) REFERENCES DONDH(SoDH),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

-- Bảng quan hệ giữa đơn đặt hàng và nhà cung cấp
CREATE TABLE CUNG_CAP (
    MaNCC VARCHAR(20),
	SoDH VARCHAR(20),
    PRIMARY KEY (SoDH, MaNCC),
    FOREIGN KEY (SoDH) REFERENCES DONDH(SoDH),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);

-- Bảng SDT lưu số điện thoại cho từng nhà cung cấp
CREATE TABLE SDT (
    MaNCC VARCHAR(20),
    SDT VARCHAR(20),
    PRIMARY KEY (MaNCC, SDT),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);
